### ISSUE TITLE
Error in react native setup

### ISSUE THREAD

**Issue by karendelakaren** [oberonamsterdam/create-react-stack#14]
After the react native setup it gives me the following error: 

```
To run your app on iOS:
   cd /Users/karendegraaf/projects/createReactStack
   react-native run-ios
   - or -
   Open ios/createReactStack.xcodeproj in Xcode
   Hit the Run button
To run your app on Android:
   cd /Users/karendegraaf/projects/createReactStack
   Have an Android emulator running (quickest way to get started), or a device connected
   react-native run-android
create-react-stack ERR! Error: No files match the pattern: /Users/karendegraaf/projects/createReactStack/index.*.js
    at glob (/Users/karendegraaf/.npm/_npx/53772/lib/node_modules/create-react-stack/node_modules/replace-in-file/lib/replace-in-file.js:173:23)
    at f (/Users/karendegraaf/.npm/_npx/53772/lib/node_modules/create-react-stack/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/karendegraaf/.npm/_npx/53772/lib/node_modules/create-react-stack/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:115:13)
    at Glob.emit (events.js:210:7)
    at Glob._finish (/Users/karendegraaf/.npm/_npx/53772/lib/node_modules/create-react-stack/node_modules/glob/glob.js:197:8)
    at done (/Users/karendegraaf/.npm/_npx/53772/lib/node_modules/create-react-stack/node_modules/glob/glob.js:182:14)
    at Glob._processReaddir2 (/Users/karendegraaf/.npm/_npx/53772/lib/node_modules/create-react-stack/node_modules/glob/glob.js:408:12)
    at /Users/karendegraaf/.npm/_npx/53772/lib/node_modules/create-react-stack/node_modules/glob/glob.js:371:17
    at RES (/Users/karendegraaf/.npm/_npx/53772/lib/node_modules/create-react-stack/node_modules/inflight/inflight.js:31:16)
```

**Comment by jariz** [comment]
Fixed w/ #15
